"use client";
import { Inter } from 'next/font/google'
import './globals.css'
import ParticleBackground from './components/Particles'
import Navbar from './components/Header';
import ReduxProvider from "../../store/ReduxProvider";
import Alert from "./components/Alert";

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`gradient_background min-h-screen ${inter.className}`}>
        <ReduxProvider>
          <Navbar/>
          <ParticleBackground />
          <Alert/>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
